let suggestions = [
    "Game Boy Color",
    "Game Boy Advance",
    "Atari 2600",
    "PS2",
    "NES",
    "SNES",
    "Final Fantasy IX",
    "Golden Eye 007",
    "Super Mario Bros 3",
    "The Legend Of Zelda Ocarina Of Time",
    "Pokémon Red",
    "Resident Evil 2 N64",
    "Disoc Duro Externo 4TB",
    "Control PS4",
    "Control PS5",
    "Control XBOX One",
    "Control WII U Pro",
    "Diadema Blu",
    "Kratos",
    "Yoshi",
    "Link",
    "Mario Tanooki",
];